### PR TITLE
add debugging to animals example

### PR DESCRIPTION
**Pull request by geoffreylitt**

### CODE REVIEW

**Comment by geoffreylitt** [comment]
Maybe instead of replacing the previous example, we want to leave the old one alone as a simple starting point for newcomers, and make this a separate thing?

**Comment by jedahan** [comment]
Yeah I think having this be a separate debugger example would be best. I think incremental examples are best, as they more closely follow our own development experience.

**Comment by geoffreylitt** [comment]
Alright, I updated to keep the simple example as "animals", and then made this a new example "animals-with-debugger".

**Comment by jedahan** [comment]
Is splitting the js from the html for the animals.html for syntax highlighting? I figure if the entire 'app' can fit in under 100 lines, then its kinda nice to be all in one file. Either way, I'm merging as is and we can discuss that later.

**Comment by geoffreylitt** [comment]
Yeah, the separate file just worked better with my editor. Mainly for syntax highlighting; also was trying out Light Table and interactively evaluating Javascript in a connected browser.

In any case, no strong preference and totally happy if you want to just move it back into one file!

**Pull request merged**
